---
title: About this site
---

Hello!
My name is Linus Arver and this is my blog. I originally started a blog about
various programming-related things [[https://zuttobenkyou.wordpress.com/][here]], but I wanted more control over how the
content is generated/stored, and so I created this site. The source code for it
(static content generator) is [[https://github.com/listx/listx_blog][here]], and the generated output (the static
content) is [[https://github.com/listx/listx.github.io][here]].

* On Programming

I have way too much fun writing computer programs.
It is by far my favorite hobby, ever since I rediscovered it in 2009.
There's just something about making the computer solve your problems that just
never gets old...!

* Recommended Software

I use free/open-source software almost exclusively as much as possible.
Below are some of them.

- [[https://nixos.org][NixOS]] - my favorite OS
- [[https://github.com/LnL7/nix-darwin][nix-darwin]] - gives you NixOS-like
  configuration for your Mac
- [[https://github.com/eigilnikolajsen/commit-mono][Commit Mono]] - my favorite
  monospaced font
- [[https://github.com/wez/wezterm][WezTerm]] - a terminal emulator,
  configurable with Lua
- [[https://github.com/tmux/tmux][tmux]] - terminal multiplexer
- [[http://xmonad.org/][xmonad]] - the crash-proof tiled window manager
- [[https://github.com/emacs-mirror/emacs][Emacs]] - an advanced text editor
- [[https://github.com/doomemacs/doomemacs][Doom Emacs]] - Emacs with batteries
  included
- [[https://github.com/The-Compiler/qutebrowser][Qutebrowser]] - a lightweight
  browser with Vim bindings
- [[https://orgmode.org/][Org Mode]] - sufficiently flexible note-taking system
- [[https://www.tug.org/texlive/][TeX Live]] - programmable typesetting

* Elsewhere on the Web

** Git Rev News: Edition 109 (March 31st, 2024) Developer Spotlight

Some months after I started contributing to Git, the community kindly asked me
for [[https://git.github.io/rev_news/2024/03/31/edition-109/#developer-spotlight-linus-arver][an interview]]. What an honor!

** The Great "k8s.gcr.io" Vanity Domain Flip (November 2020)

*[[https://www.youtube.com/watch?v=F2IFjz7sr9Q][Video]]*

A tale about what happened behind the scenes in the Kubernetes community
infrastructure-wise in 2019-2020, while the rest of the world slept.  Special
thanks to [[https://www.linkedin.com/in/stephenaugustus/][Stephen Augustus]] from VMware who pitched the idea for the talk
initially and helping with the recording as well.

** Git: Your Favorite Tool (July 2015)

*[[https://github.com/listx/listx_blog/blob/master/file/git.org][Source]]*, *[[https://github.com/listx/listx_blog/blob/master/file/git.pdf][PDF]]*

These slides are from a talk I gave internally at [[https://twinprime.com/][Twin Prime]] (they were later
acquired by SalesForce).  I designed the slides so that they are readable as-is,
without a real presentation.  Last but not least, I hereby release these slides
into the Public Domain --- do whatever you like with them!

** Bitscans and De Bruijn Sequences (2014)

*[[https://github.com/listx/listx_blog/blob/master/file/debruijn-sequence-tutorial.pdf][PDF]]*

I wrote this paper originally in 2011--2012, but it was not released until it
was finally revised in 2014.

* Contact

Please email me at [[mailto:linus@ucla.edu][linus@ucla.edu]] for anything related to this blog. I have long
since graduated from UCLA, but they gave me a lifetime email address. Thank you,
UCLA!

** Accounts on other sites

Somewhat active:

- [[https://www.linkedin.com/in/linusarver/][LinkedIn]]
- [[https://github.com/listx][GitHub]] (=listx=)
- [[https://exercism.org/profiles/listx][Exercism]] (=listx=)
- [[https://online-go.com/player/213337][Online Go Server]] (=funloop=)
- [[https://www.reddit.com/user/listx][Reddit]] (=listx=)

Historical artifacts:

- [[https://www.deviantart.com/magic-byte][DeviantArt]] (=magic-byte=)
- [[https://twitter.com/linusarver][Twitter]]
- [[https://zuttobenkyou.wordpress.com/][Wordpress (old blog)]]
