---
title: Development Best Practices
tags: programming
---

#+STARTUP: indent showall
#+OPTIONS: ^:nil

This is a summary of the article [[http://arxiv.org/abs/1210.0530][/Best
Practices for Scientific Computing/ (Greg Wilson et. al, 2012)]]. I
think the points raised have importance in software development
practices in general. A lot of the material resonated with me as a
developer, and I recommend you read it or my condensed version (with my
embedded comments) below.

* Write Programs for People, Not Computers
   :PROPERTIES:
   :CUSTOM_ID: write-programs-for-people-not-computers
   :END:

*** A program should not require its readers to hold more than a handful of facts in memory at once.
     :PROPERTIES:
     :CUSTOM_ID: a-program-should-not-require-its-readers-to-hold-more-than-a-handful-of-facts-in-memory-at-once.
     :END:

Instead of

#+BEGIN_EXAMPLE -n
  def rect_area(x1, y1, x2, y2):
      ...calculation...
#+END_EXAMPLE

write

#+BEGIN_EXAMPLE -n
  def rect_area(point1, point2):
      ...calculation...
#+END_EXAMPLE

. You should make function arguments less dependent on argument order,
or remove argument ordering requirements completely.

*** Names should be consistent, distinctive, and meaningful.
     :PROPERTIES:
     :CUSTOM_ID: names-should-be-consistent-distinctive-and-meaningful.
     :END:

On a similar note, do not name variables "data" or "foo". I think this
also depends on static vs. dynamic typing.[fn:1]

*** Code style and formatting should be consistent.
     :PROPERTIES:
     :CUSTOM_ID: code-style-and-formatting-should-be-consistent.
     :END:

Be like the Linux Kernel project --- use a single coding style.

*** All aspects of software development should be broken down into tasks roughly an hour long.
     :PROPERTIES:
     :CUSTOM_ID: all-aspects-of-software-development-should-be-broken-down-into-tasks-roughly-an-hour-long.
     :END:

Our brains start to lose focus after 60-90 minutes of performing an
intense activity.

* Automate Repetitive Tasks
   :PROPERTIES:
   :CUSTOM_ID: automate-repetitive-tasks
   :END:

*** Rely on the computer to repeat tasks.
     :PROPERTIES:
     :CUSTOM_ID: rely-on-the-computer-to-repeat-tasks.
     :END:

Write shell scripts if you need to.

*** Save recent commands in a file for re-use.
     :PROPERTIES:
     :CUSTOM_ID: save-recent-commands-in-a-file-for-re-use.
     :END:

Take advantage of your shell's ability to save history.

*** Use a build tool to automate workflows.
     :PROPERTIES:
     :CUSTOM_ID: use-a-build-tool-to-automate-workflows.
     :END:

You can use /GNU Make/ not only to compile code, but to describe a
dependency graph of your workflow (do X before Y).

* Use the Computer to Record History
   :PROPERTIES:
   :CUSTOM_ID: use-the-computer-to-record-history
   :END:

*** Software tools should be used to track computational work automatically, to achieve provenance.
     :PROPERTIES:
     :CUSTOM_ID: software-tools-should-be-used-to-track-computational-work-automatically-to-achieve-provenance.
     :END:

To reproduce your results, you should record everything needed to
re-create the output[fn:2], and such record-keeping should be done
automatically. In a software development context, the most immediate
example is version control, which keeps all of the code necessary to
recreate the desired program behavior. However, there are several other
things which you should also keep track of in your development notebook:

- UUIDs and version numbers for raw data records (e.g., sample
  parameters/input for your program);
- UUIDs and version numbers for programs and libraries;
- the values and parameters used to generate any given output; and
- the names and version numbers of programs (however small) used to
  generate those outputs.

This is not entirely on point, but every Linux distribution keeps
careful records of all packages (dependencies, version numbers, etc.),
so that a user can reliably install and use that package if they want
to. There is a lesson to be learned here.

* Make Incremental Changes
   :PROPERTIES:
   :CUSTOM_ID: make-incremental-changes
   :END:

*** Work in small steps with frequent feedback and course correction.
     :PROPERTIES:
     :CUSTOM_ID: work-in-small-steps-with-frequent-feedback-and-course-correction.
     :END:

Do not plan months or years of work in advance. The goal is to produce
working (but incomplete) code after each iteration.

* Use Version Control
   :PROPERTIES:
   :CUSTOM_ID: use-version-control
   :END:

*** Use a version control system.
     :PROPERTIES:
     :CUSTOM_ID: use-a-version-control-system.
     :END:

Again, note that version control gives you provenance for you program's
behavior /throughout its development history/, so that you can always
reproduce the behavior at any given point in time. Version control gives
you provenance for your program --- it's just that powerful.

*** Everything that has been created manually should be put in version control.
     :PROPERTIES:
     :CUSTOM_ID: everything-that-has-been-created-manually-should-be-put-in-version-control.
     :END:

Large binary files should still be recorded (git-annex comes to mind).
If you don't want to use git-annex, just write down the SHA1 hash of the
binary file, and commit this hash number into your version control. Add
in a test suite that checks for the correct hashes of these binary
files, and you're all set!

* Don't Repeat Yourself (or Others)
   :PROPERTIES:
   :CUSTOM_ID: dont-repeat-yourself-or-others
   :END:

*** Every piece of data must have a single authoritative representation in the system.
     :PROPERTIES:
     :CUSTOM_ID: every-piece-of-data-must-have-a-single-authoritative-representation-in-the-system.
     :END:

E.g., define the constant =pi= once in your program, and always use =pi=
when you mean it. Likewise, you should try to refactor your variables so
that they lead down to a single source.

*** At small scales, code should be modularized rather than copied and pasted.
     :PROPERTIES:
     :CUSTOM_ID: at-small-scales-code-should-be-modularized-rather-than-copied-and-pasted.
     :END:

Modularized code can also be more easily repurposed for other projects.

*** At large scales, re-use code instead of rewriting it.
     :PROPERTIES:
     :CUSTOM_ID: at-large-scales-re-use-code-instead-of-rewriting-it.
     :END:

Use libraries for not-so-trivial problems outside of your comfort zone
(e.g., 3D graphics).

* Plan for Mistakes
   :PROPERTIES:
   :CUSTOM_ID: plan-for-mistakes
   :END:

** Defensive Programming
    :PROPERTIES:
    :CUSTOM_ID: defensive-programming
    :END:

*** Add assertions to programs to check their operation.
     :PROPERTIES:
     :CUSTOM_ID: add-assertions-to-programs-to-check-their-operation.
     :END:

Assertions are great because they simplify debugging by making your
program halt as soon as one of them gets triggered. Even better, they
serve as /executable documentation/, which by their nature /never become
obsolete/.

*** Use automated testing.
     :PROPERTIES:
     :CUSTOM_ID: use-automated-testing.
     :END:

At small scales (single functions, components) unit tests are handy. At
larger scales, employ /integration testing/: tests that check multiple
components working together. I personally recommend randomized stress
testing, a la QuickCheck. /Regression testing/ is the practice of
running pre-existing tests after changes to the code in order to make
sure that nothing has broken.

Do not practice test-driven development (TDD), where you write tests
before writing any new code, because a meta-study of its effectiveness
done in 2010 did not find any significant impact on programmer
productivity.[fn:3]

*** Use an off-the-shelf testing library.
     :PROPERTIES:
     :CUSTOM_ID: use-an-off-the-shelf-testing-library.
     :END:

Use of a testing library encourages us to write testable code, which
generally means cleaner functions and less spaghetti code. If you're
working with a legacy code base without tests, a great way to refactor
it is to make parts of it testable.

** Use a Variety of Oracles
    :PROPERTIES:
    :CUSTOM_ID: use-a-variety-of-oracles
    :END:

An oracle is something which tells a developer how a program should
behave or what its output should be. Define generally expected program
behavior and make sure your code conforms to it. All of this can be done
in an automated way with a good testing suite, but you can also manually
write down a spec (probably as part of the documentation) and make sure
your program performs as advertised, in all situations.

** Turn bugs into test cases
    :PROPERTIES:
    :CUSTOM_ID: turn-bugs-into-test-cases
    :END:

Write a test that will trigger the bug, and then fix your code to kill
the bug. This is an easy and simple way to write a regression test.

** Use a debugger
    :PROPERTIES:
    :CUSTOM_ID: use-a-debugger
    :END:

The more complex your code becomes, the more important it is to
familiarize yourself with a debugger.

* Optimize Software Only After it Works Correctly
   :PROPERTIES:
   :CUSTOM_ID: optimize-software-only-after-it-works-correctly
   :END:

*** Use a profiler to identify bottlenecks accurately.
     :PROPERTIES:
     :CUSTOM_ID: use-a-profiler-to-identify-bottlenecks-accurately.
     :END:

You should only care about performance /after/ you get working code.

*** Write code in the highest-level language possible.
     :PROPERTIES:
     :CUSTOM_ID: write-code-in-the-highest-level-language-possible.
     :END:

Research has confirmed that most programmers write roughly the same
number of lines of code per unit time regardless of the language they
use.[fn:4] Thus, you should try to write code in a high level language
to save development time and increase productivity, and then fall back
to a low level language to a speed boost where necessary.

* Document Design and Purpose, Not Mechanics
   :PROPERTIES:
   :CUSTOM_ID: document-design-and-purpose-not-mechanics
   :END:

*** Document interfaces and reasons, not implementations.
     :PROPERTIES:
     :CUSTOM_ID: document-interfaces-and-resons-not-implementations.
     :END:

It is more useful to explain why code is written a certain way, instead
of explaining the mechanics behind the implementation, for the code will
speak for itself in the case of the latter. If the code cannot speak for
itself, then see the point below.

*** Refactor code instead of explaining how it works.
     :PROPERTIES:
     :CUSTOM_ID: refactor-code-instead-of-explaining-how-it-works.
     :END:

Reorganize complex code so that it doesn't even need an explanation.

Literate programming might be a good approach to fuse documentation and
code together, but I personally have no experience with LP.

* Collaborate
   :PROPERTIES:
   :CUSTOM_ID: collaborate
   :END:

*** Use pre-merge code reviews.
     :PROPERTIES:
     :CUSTOM_ID: use-pre-merge-code-reviews.
     :END:

Code reviews are highly effective, but you should do it before the
merge. Once code gets merged, there is little incentive to review it,
because hey, nothing's broken, right?

*** Use pair programming when bringing someone new up to speed and when tackling particularly tricky problems.
     :PROPERTIES:
     :CUSTOM_ID: use-pair-programming-when-bringing-someone-new-up-to-speed-and-when-tackling-particularly-tricky-problems.
     :END:

Pair programming can be intrusive, so take it with a grain of salt.

*** Use an issue tracking tool.
     :PROPERTIES:
     :CUSTOM_ID: use-an-issue-tracking-tool.
     :END:

There are lots of free issue tracking tools available, not to mention
sites like GitHub/Gitorious/BitBucket that integrate online
collaboration, sharing, issue tracking, etc. all into one package.

* Conclusion
   :PROPERTIES:
   :CUSTOM_ID: conclusion
   :END:

In my opinion, the holy trinity in software development is composed of
(1) version control, (2) automated testing, and (3) documentation. If
you have these three, you are already golden and the rest is icing on
the cake.

[fn:1] In Haskell (static typing), people routinely name variables "a"
       or "b" with no fear of confusion, thanks to type signatures.

[fn:2] /Provenance/ is term from archaeology and forensics.

[fn:3] Burak Turhan, Lucas Layman, Madeline Diep, Hakan Erdogmus, and
       Forrest Shull. /How Effective is Test-Driven Development?/ In
       Andy Oram and Greg Wilson, editiors, /Making Software: What
       Really Works, and Why We Believe It/, pp. 207-217. O'Reilly, 2010.

[fn:4] See Lutz Prechelt. /Two Comparisons of Programming Languages./ In
       Andy Oram and Greg Wilson, editiors, /Making Software: What
       Really Works, and Why We Believe It/. O'Reilly, 2010.
